tags: "att_conv_unet_AdamW_GCC"
title: "conv_unet_AdamW_GCC"
epochs_num: 100
batch_size: 100
model_name: "att_conv_unet"
model_in_channels: 3
model_out_channels: 9
base_dir_path: "att_conv_unet_AdamW_GCC"
dataset_path: "J:/deepcloth/datasets/human_body_parsing/kjn_parse_dataset"
checkpoint_path: ""
optim_type: "AdamW_GCC"
lr: 0.0001
cross_entropy_loss_lambda: 10
iou_loss_lambda: 10
canny_loss_lambda: 10
