tags: "squeezenet_Adam_GCC"
title: "squeezenet_Adam_GCC"
epochs_num: 10
batch_size: 16
model_name: "squeezenet"
model_in_channels: 3
model_out_channels: 9
base_dir_path: "squeezenet_Adam_GCC"
dataset_path: "J:/deepcloth/datasets/human_body_parsing/kjn_parse_dataset_001"
checkpoint_path: ""
optim_type: "AdamW_GCC"
lr: 0.0001
